# NumPy를 활용한 선형대수 입문
### <<중요 개념>>
#### 스칼라, 벡터, 행렬
#### 열, 행, 차원
#### 특정 벡터, 특정 행렬
#### 전치 연산
#### 영 벡터, 열 벡터, 정방 행렬, 대각 행렬, 단위 행려르 대칭 행렬

# 1. 데이터의 유형
## >> 스칼라(scalar), 벡터(vecotr), 행렬(matrix)

## 1) 스칼라
#### >> 스칼라는 하나의 숫자만으로 이루어진 데이터

## 2) 벡터
#### >> 벡터는 여러 개의 숫자가 특정한 순서대로 모여 있는 것
#### >> NumPy를 사용할 때는 벡터를 열의 개수가 하나인 2차원 배열 객체로 표현하는 것이 올바른 표현
#### >> 하지만 대부분의 경우에 NumPy는 1차원 배열 객체도 벡터로 인정한다. 이 경우에는 벡터가 마치 하나의 행처럼 표시되어도 실제로는 열의 의미를 가진다는 점에 주의한다.
#### >> Scikit-learn 패키지에서 벡터를 요구하는 경우에는 반드시 열의 갯수가 1개인 2차원 배열 객체를 넣어야 한다.

In [1]:
import numpy as np

In [2]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x1

array([[ 5.1],
       [ 3.5],
       [ 1.4],
       [ 0.2]])

In [3]:
x1 = np.array([5.1, 3.5, 1.4, 0.2])
x1

array([ 5.1,  3.5,  1.4,  0.2])

# 연습문제1.
### NumPy를 사용해서 붓꽃데이터 x2에 대한 벡터 변수 x2를 만든다.

In [4]:
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2

array([[ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2]])

## 3) 행렬
#### >> 행렬은 복수의 차원을 가지는 데이터 레코드가 다시 여러 개 있는 경우의 데이터를 합쳐서 표기한 것
#### >> 행렬의 원소 하나하나는  x2,3x2,3 처럼 두 개의 숫자 쌍을 아래첨자(sub-script)로 붙여서 표기
#### >> 벡터는 열의 수가 1인 행렬이라고 볼 수 있기 때문에 벡터를 다른 말로 열 벡터(column vector)
#### >> 데이터를 행렬로 묶어서 표시할 때는 붓꽃 하나에 대한 데이터 레코드, 즉 하나의 벡터가 열이 아닌 행(row)으로 표시한다. 
#### >> 하나의 데이터 레코드를 단독으로 벡터로 나타낼 때는 하나의 열(column)로 나타내고 복수의 데이터 레코드 집합을 행렬로 나타낼 때는 하나의 데이터 레코드가 하나의 행(row)으로 표기
#### >> ndarray 객체 : NumPy를 이용하여 행렬을 표기할 때 사용하는 2차원 ndarray 객체 

In [5]:
A = np.array([[11, 12, 13], [21, 22, 23]])
A

array([[11, 12, 13],
       [21, 22, 23]])

# 연습문제2
### NumPy를 사용해서 붓꽃 데이터 X에 대한 행렬 변수 X를 만든다.

In [6]:
X = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

# 전치 연산
#### >> 행과 열을 바꾸는 연산
#### >> NumPy에서는 ndarray 객체의 T라는 속성을 이용하여 전치 행렬을 구한다. 이 때 T는 메서드(method)가 아닌 속성(attribute)이므로 ()를 붙여서 호출하면 안된다.
#### >> 1차원 ndarray는 전치 연산이 정의되지 않는다.

In [7]:
A.T

array([[11, 21],
       [12, 22],
       [13, 23]])

In [8]:
x1

array([ 5.1,  3.5,  1.4,  0.2])

In [9]:
x1.T

array([ 5.1,  3.5,  1.4,  0.2])

# 연습 문제3
### 1. NumPy를 사용해서 붓꽃데이터 X의 전치행렬 XT를 구한다.
### 2. 전치행렬을 다시 전치한 행렬 (Xt)t을 구한다. 이 행렬과 원래 행렬 X을 비굑

In [10]:
X.T

array([[ 5.1,  4.9],
       [ 3.5,  3. ],
       [ 1.4,  1.4],
       [ 0.2,  0.2]])

In [11]:
(X.T).T

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

In [13]:
X # 전치항 행렬에 다시 전치한 것과 동일

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

# 행렬의 행 표기법과 열 표기법

# 특수한 벡터와 행렬
### 1. 영벡터 : 모든 원소가 0인 N차원 벡터
### 2. 일벡터 : 모든 원소가 1인 N차원 벡터
### 3. 정방 행렬(square matrix) : 행의 크기와 열의 크기가 같은 행렬
### 4. 대각행렬(diagonal matrix) : 모든 비대각 요소가 0인 정방행렬
### 5. 단위 행렬(identity matrix) : 대각행렬중에서 모든 대각 성분의 값이 1인 대각행렬
### 6. 대칭행렬(symmetric matrix) : 전치 연산을 통해서 얻어진 전치행렬과 원래의 행렬이 같은 정방행렬

In [14]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# 연습문제4
### 1. 영벡터, 일벡터, 정방행렬, 대각행렬, 단위행렬, 대칭행렬의 예를 하나씩 만들어 본다.
### 2. 위의 벡터와 행렬을 NumPy로 나타내본다.

In [17]:
zero=np.zeros(5)
zero

array([ 0.,  0.,  0.,  0.,  0.])

In [18]:
one=np.ones(5)
one

array([ 1.,  1.,  1.,  1.,  1.])

In [26]:
sm = np.random.randint(50,size=(5,5))
sm

array([[31,  9, 11, 19, 43],
       [23, 15,  3,  4, 39],
       [41, 21, 48, 49, 48],
       [ 8, 31, 24, 31,  4],
       [12, 11, 27, 14, 11]])

In [29]:
dm = np.arange(25).reshape((5,5))
dm

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
np.diag(dm)

array([ 0,  6, 12, 18, 24])

In [32]:
np.diag(np.diag(dm))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [33]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [35]:
def symmetricize(arr):
    de = np.arange(arr.size)
    return arr[np.abs(de - de[:,None])]

In [41]:
arr = np.random.randint(30, size=5)
arr

array([18, 17, 22, 18, 13])

In [42]:
symmetricize(arr)

array([[18, 17, 22, 18, 13],
       [17, 18, 17, 22, 18],
       [22, 17, 18, 17, 22],
       [18, 22, 17, 18, 17],
       [13, 18, 22, 17, 18]])