In [1]:
import numpy as np

In [3]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(a)

numpy.ndarray

In [5]:
a=[0,1,2,3,4,5,6,7,8,9]

In [6]:
b=[]
for ai in a:
    b.append(ai*2)
b

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [7]:
x=np.array(a) # 벡터화 연산을 사용하면 더 빠르고 편함.(for문 사용할 필요도 없음.)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
L = [0,1,2,3,4,5,6,7,8,9]
print(2*L) # L의 원소들의 (개수)에 *2 - 반복

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
a=np.array([1,2,3])
b=np.array([10, 20, 30])
2*a+b # 원소에 대해 사칙연산

array([12, 24, 36])

In [13]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [15]:
np.log(b)

array([ 2.30258509,  2.99573227,  3.40119738])

In [16]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001])

In [17]:
b=np.array([[0,1,2], [3,4,5]]) # 2x3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
len(b) # rows

2

In [20]:
len(b[0]) # columns

3

In [23]:
#연습문제1
mt = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
mt

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [24]:
c=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [25]:
len(c) # 가장 크게 2개

2

In [26]:
len(c[0]) # 그 다음 안에 개수 3개(배열)

3

In [27]:
len(c[0][0]) # 가장 안의 배열의 원소 수 

4

In [30]:
print(a.ndim)
print(a.shape)

1
(3,)


In [31]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [32]:
print(c.ndim)
print(c.shape)

3
(2, 3, 4)


In [33]:
a=np.array([[0,1,2], [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
a[0,0] # a first row first column

0

In [35]:
a[0,1] # first row second column

1

In [36]:
a[-1,-1]

5

In [55]:
a=np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
a[0,:]

array([0, 1, 2, 3])

In [57]:
a[:,1]

array([1, 5])

In [58]:
a[1,1:]

array([5, 6, 7])

In [59]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [46]:
#연습문제2.
m = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
#1. 이 행렬에서 값 7을 인덱싱 한다.
m[1,2]

7

In [67]:
#2. 이 행렬에서 값 14을 인덱싱한다.
m[2,4]

14

In [70]:
#3. 이 행렬에서 배열[6,7]을 슬라이싱한다.
m[1,1:3]

array([6, 7])

In [75]:
#4. 이 행렬에서 배열 [7,12]을 슬라이싱한다.
m[1:3,2]

array([ 7, 12])

In [78]:
#5. 이 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱한다.
m[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [80]:
#배열 인덱싱
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([0, 2, 4, 6, 8])

In [81]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [83]:
a=np.array([0,1,2,3,4,5,6,7,8,9])*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
idx=np.array([0,2,4,6,8]) # 정수 배열 인덱스 크기는 원래 배열 크기와 달라도 상관없엄.
a[idx]

array([ 0, 20, 40, 60, 80])

In [85]:
a = np.array([0,1,2,3])*10
idx=np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([ 0,  0,  0,  0,  0,  0, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20])

In [94]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
a_list = np.array([True,False,False,True]) #future warning
a[:, a_list]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [88]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])