# NumPy의 역행렬 계산
### NumPy의 Linalg 서브패키지 -> inv(역행렬 계산)
### 실제 계산시에는 수치해석 상의 여러 문제 -> lstsq(least square) 사용

In [1]:
import numpy as np

In [2]:
A = np.array([[1,3,-2], [3,5,6], [2,4,3]])
A

array([[ 1,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3]])

In [7]:
b = np.array([[5], [7], [8]])
b

array([[5],
       [7],
       [8]])

In [8]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 2.25,  4.25, -7.  ],
       [-0.75, -1.75,  3.  ],
       [-0.5 , -0.5 ,  1.  ]])

In [9]:
x = np.dot(Ainv, b)
x

array([[-15.],
       [  8.],
       [  2.]])

In [10]:
np.dot(A, x) - b

array([[ -3.55271368e-15],
       [ -1.42108547e-14],
       [ -1.42108547e-14]])

In [11]:
x, resid, rank, s = np.linalg.lstsq(A,b)
x

array([[-15.],
       [  8.],
       [  2.]])

# 행렬식의 값이 0이 아니면 역행렬이 존재한다. 반대로 역행렬이 존재하면 행렬식의 값은 0이 아니다. 

# 최소 자승 문제 

In [13]:
A = np.array([[2, 0], [-1, 1], [0, 2]])
A

array([[ 2,  0],
       [-1,  1],
       [ 0,  2]])

In [14]:
b=np.array([[1], [0], [-1]])
b

array([[ 1],
       [ 0],
       [-1]])

In [15]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T,A)), A.T)
Apinv

array([[ 0.41666667, -0.16666667,  0.08333333],
       [ 0.08333333,  0.16666667,  0.41666667]])

In [16]:
x = np.dot(Apinv, b)
x

array([[ 0.33333333],
       [-0.33333333]])

In [17]:
np.dot(A, x) - b

array([[-0.33333333],
       [-0.66666667],
       [ 0.33333333]])

In [18]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[ 0.33333333],
       [-0.33333333]])