# NumPy를 사용한 난수 발생과 카운팅
### << 중요 개념 >>
### np.random.seed
### np.random.rand, np.random.randint, np.random.randn
### np.random.shuffle, np.random.choice
### np.unique, np.bincount

In [1]:
import numpy as np

## 시드 설정하기

In [20]:
np.random.seed(0) # 같은 값으로 시작하도록

In [21]:
np.random.rand(5)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])

In [22]:
np.random.rand(10)

array([ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152,
        0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606])

In [23]:
np.random.rand(10)

array([ 0.0871293 ,  0.0202184 ,  0.83261985,  0.77815675,  0.87001215,
        0.97861834,  0.79915856,  0.46147936,  0.78052918,  0.11827443])

In [24]:
np.random.seed(0)

In [26]:
np.random.rand(5)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])

In [27]:
np.random.rand(10)

array([ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152,
        0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606])

In [28]:
np.random.rand(10)

array([ 0.0871293 ,  0.0202184 ,  0.83261985,  0.77815675,  0.87001215,
        0.97861834,  0.79915856,  0.46147936,  0.78052918,  0.11827443])

## 기존의 데이터의 순서 바꾸기

In [29]:
x = np.arange(10)
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])


## 기존의 데이터에서 샘플링하기
### a : 배열이면 원래의 데이터, 정수이면 range(a) 명령으로 데이터 생성
### size : 정수. 샘플 숫자
### replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능
### p : 배열. 각 데이터가 선택될 수 있는 확률

In [30]:
np.random.choice(5, 5, replace=False) # shuffle명령고 동일

array([1, 4, 0, 3, 2])

In [31]:
np.random.choice(5, 3, replace=False) # 3개만 선택

array([2, 1, 3])

In [33]:
np.random.choice(5, 10) # 반복해서 10개 선택

array([1, 1, 3, 3, 2, 3, 0, 3, 4, 1])