# 벡터와 행렬의 연산
## << 중요 개념 >>
### 벡터의 곱셈(내적)
### 가중합, 제곱합
### 선형 회귀 모형
### 행렬의 곱셈(내적)
### 교환 법칙, 분배 법칙
### 잔차, 잔차 제곱합
### 이차 형식

# 1. 벡터와 행렬의 덧셈과 뺄셈

In [1]:
import numpy as np

In [2]:
x = np.array([10, 11, 12, 13, 14])
x

array([10, 11, 12, 13, 14])

In [3]:
y = np.array([0, 1, 2, 3, 4])
y

array([0, 1, 2, 3, 4])

In [4]:
x + y

array([10, 12, 14, 16, 18])

In [5]:
x - y

array([10, 10, 10, 10, 10])

# 2. 벡터의 곱셈(내적)
#### >> 벡터의 곱셈에는 내적(inner product)과 외적(outer product) 등 여러 가지 곱셈 방법
#### >> 내적은 점(dot)으로 표기하는 경우도 있어서 dot product라고 하기도 한다.
### << 조건 >>
#### 1. 우선 두 벡터의 길이가 같아야 하고
#### 2. 앞의 벡터가 행 벡터이고 뒤의 벡터가 열 벡터여야 한다.

# 3. 가중합
#### >> 가중합(weighted sum)이란 복수의 데이터를 단순히 합하는 것이 아니라 각각의 수에 어떤 가중치 값을 곱한 후 이 곱셈 결과들을 다시 합한 것
#### >> NumPy에서 벡터와 행렬의 곱은 dot 이라는 명령으로 계산
#### >> NumPy에서는 결과 값이 스칼라가 아니라 1x1 크기의 2차원 배열 즉, 행렬로 표시되는 점에 주의한다.
#### >> 원래 내적은 크기가 같은 행 벡터와 열 벡터에 대해 정의되지만 NumPy에서는 1차원 배열끼리도 곱할 수 있다. 이 때는 NumPy가 자동적으로 앞의 벡터는 행 벡터이고 뒤의 벡터는 열 벡터라고 가정

In [6]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])
np.dot(x.T, y)

array([[32]])

In [7]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.dot(x,y)

32

# 4. 평균
#### >> 가중치 값이 1/N인 가중 평균과 같아

In [8]:
x = np.arange(10)
x.mean()

4.5

In [10]:
N = len(x)
np.dot(np.ones(N), x) / N

4.5

# 5. 제곱합

# 6. 선형 회귀 모형
#### >> 독립 변수  xx 에서 종속 변수  yy 를 예측하기 위한 방법의 하나로 독립 변수 벡터  xx  와 가중치 벡터  ww 와의 가중합으로  yy 와 가장 비슷한 값  y^y^ 를 계산하는 수식

# 7. 행렬의 곱셈(내적)

In [11]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3, 4], [5, 6]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
C = np.dot(A, B)
C

array([[22, 28],
       [49, 64]])

# 연습문제1

In [16]:
D = np.dot(B, A)
D

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [30]:
A = np.array([1,2,3])
B = np.array([[4, 7], [5, 8], [6, 9]])

In [31]:
A

array([1, 2, 3])

In [32]:
B

array([[4, 7],
       [5, 8],
       [6, 9]])

In [33]:
C = np.dot(A, B)
C

array([32, 50])

In [34]:
D = np.dot(B, A)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [35]:
A = np.array([[1,2], [3, 4]])
B = np.array([[5,6], [7,8]])

In [36]:
A

array([[1, 2],
       [3, 4]])

In [37]:
B

array([[5, 6],
       [7, 8]])

In [38]:
C = np.dot(A, B)
C

array([[19, 22],
       [43, 50]])

In [39]:
D = np.dot(B, A)
D

array([[23, 34],
       [31, 46]])

In [40]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [41]:
np.dot(x.T, x)

array([[14]])

In [42]:
np.dot(x, x.T)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

# 교환 법칙과 분배 법칙

In [43]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])

In [44]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [45]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [46]:
np.dot(A, B+C)

array([[42, 42],
       [98, 98]])

In [47]:
np.dot(A, B) + np.dot(A, C)

array([[42, 42],
       [98, 98]])

In [48]:
np.dot(A + B, C)

array([[110,  96],
       [174, 152]])

In [49]:
np.dot(A, C) + np.dot(B, C)

array([[110,  96],
       [174, 152]])

In [50]:
(A + B).T

array([[ 6, 10],
       [ 8, 12]])

In [51]:
A.T + B.T

array([[ 6, 10],
       [ 8, 12]])

In [52]:
(np.dot(A, B)).T

array([[19, 43],
       [22, 50]])

In [53]:
np.dot(B.T, A.T)

array([[19, 43],
       [22, 50]])

# 곱셈의 연결
# 연습문제2

In [54]:
A = np.array([1,2])
B = np.array([[1,2], [3,4]])
C = np.array([[5], [6]])

In [57]:
np.dot(A,B)

array([ 7, 10])

In [59]:
np.dot(A, (B + C))

array([24, 27])

In [60]:
np.dot(A, B) + np.dot(B, C)

array([[24, 27],
       [46, 49]])

In [61]:
np.dot(B.T, A.T)

array([ 7, 10])

# 단위 행렬의 곱셈

In [64]:
A = np.array([[1,2], [3,4]])
I = np.eye(2)

In [65]:
np.dot(A, I)

array([[ 1.,  2.],
       [ 3.,  4.]])

In [66]:
np.dot(I, A)

array([[ 1.,  2.],
       [ 3.,  4.]])

# 여러개의 벡터에 대한 가중합 계산

# 이차형식

In [67]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [69]:
A = np.arange(1, 10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.dot(np.dot(x, A), x)

228